"""initial_uuid_schema

Revision ID: c65541317e6f
Revises: 
Create Date: 2026-02-22 14:34:47.362805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c65541317e6f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('segment', sa.String(length=50), nullable=False),
    sa.Column('spi_value', sa.Float(), nullable=True),
    sa.Column('fcs_value', sa.Float(), nullable=False),
    sa.Column('bsi_value', sa.Float(), nullable=True),
    sa.Column('fcs_current_stability', sa.Float(), nullable=False),
    sa.Column('fcs_future_outlook', sa.Float(), nullable=False),
    sa.Column('fcs_purchasing_power', sa.Float(), nullable=False),
    sa.Column('fcs_emergency_readiness', sa.Float(), nullable=False),
    sa.Column('fcs_income_adequacy', sa.Float(), nullable=False),
    sa.Column('gf_rwi_composite', sa.Float(), nullable=False),
    sa.Column('user_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_daily_index_date', 'daily_index', ['index_date'], unique=False)
    op.create_index(op.f('ix_daily_index_id'), 'daily_index', ['id'], unique=False)
    op.create_index('ix_daily_index_segment', 'daily_index', ['segment'], unique=False)
    op.create_table('daily_indexes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('csi_close', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('dpi_close', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('frs_close', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('gci_close', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('checkin_volume', sa.Integer(), nullable=False),
    sa.Column('avg_mood_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('avg_stress_level', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('impulse_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('gci_slope_3d', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('gci_slope_7d', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('gci_volatility_7d', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('trend_direction', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', name='uq_daily_index_date')
    )
    op.create_index('ix_daily_index_date', 'daily_indexes', ['date'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('monthly_income', sa.Float(), nullable=True),
    sa.Column('monthly_expenses', sa.Float(), nullable=True),
    sa.Column('financial_goal', sa.Text(), nullable=True),
    sa.Column('subscription_tier', sa.Enum('FREE', 'PRO', 'PREMIUM', name='subscriptiontier'), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('bills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PAID', 'UPCOMING', 'OVERDUE', name='billstatus'), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills_id'), 'bills', ['id'], unique=False)
    op.create_table('checkin_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(length=10), nullable=False),
    sa.Column('dimension', sa.String(length=30), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('raw_value', sa.Integer(), nullable=False),
    sa.Column('scale_max', sa.Integer(), nullable=False),
    sa.Column('normalized_value', sa.Float(), nullable=False),
    sa.Column('checkin_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_weekly', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_checkin_resp_date', 'checkin_responses', ['checkin_date'], unique=False)
    op.create_index('ix_checkin_resp_dimension', 'checkin_responses', ['dimension'], unique=False)
    op.create_index('ix_checkin_resp_user_date', 'checkin_responses', ['user_id', 'checkin_date'], unique=False)
    op.create_index('ix_checkin_resp_user_id', 'checkin_responses', ['user_id'], unique=False)
    op.create_index(op.f('ix_checkin_responses_id'), 'checkin_responses', ['id'], unique=False)
    op.create_table('debts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('debt_type', sa.Enum('CREDIT_CARD', 'CAR_LOAN', 'STUDENT_LOAN', 'PERSONAL_LOAN', 'MORTGAGE', 'OTHER', name='debttype'), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('apr', sa.Float(), nullable=False),
    sa.Column('min_payment', sa.Float(), nullable=True),
    sa.Column('credit_limit', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debts_id'), 'debts', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.Enum('INCOME', 'RENT', 'FOOD', 'GAS', 'CREDIT_CARDS', 'INSURANCE', 'PHONE_BILL', 'UTILITIES', 'PERSONAL', 'OTHER', name='transactioncategory'), nullable=True),
    sa.Column('is_need', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_table('user_metric_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_stability', sa.Float(), nullable=False),
    sa.Column('future_outlook', sa.Float(), nullable=False),
    sa.Column('purchasing_power', sa.Float(), nullable=False),
    sa.Column('emergency_readiness', sa.Float(), nullable=False),
    sa.Column('income_adequacy', sa.Float(), nullable=False),
    sa.Column('fcs_composite', sa.Float(), nullable=False),
    sa.Column('bsi_score', sa.Float(), nullable=True),
    sa.Column('checkin_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_metric_computed', 'user_metric_snapshots', ['computed_at'], unique=False)
    op.create_index(op.f('ix_user_metric_snapshots_id'), 'user_metric_snapshots', ['id'], unique=False)
    op.create_index('ix_user_metric_user_computed', 'user_metric_snapshots', ['user_id', 'computed_at'], unique=False)
    op.create_index('ix_user_metric_user_id', 'user_metric_snapshots', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('theme', sa.Enum('DARK', 'WEALTH', 'AGGRESSIVE', 'CALM', name='theme_option'), nullable=False),
    sa.Column('risk_style', sa.Enum('CALM', 'BALANCED', 'AGGRESSIVE', name='risk_style'), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('subscription_tier', sa.String(length=32), nullable=True),
    sa.Column('feature_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('profile_completion_score', sa.Integer(), nullable=False),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_profiles_user_id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index('ix_user_metric_user_id', table_name='user_metric_snapshots')
    op.drop_index('ix_user_metric_user_computed', table_name='user_metric_snapshots')
    op.drop_index(op.f('ix_user_metric_snapshots_id'), table_name='user_metric_snapshots')
    op.drop_index('ix_user_metric_computed', table_name='user_metric_snapshots')
    op.drop_table('user_metric_snapshots')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_debts_id'), table_name='debts')
    op.drop_table('debts')
    op.drop_index(op.f('ix_checkin_responses_id'), table_name='checkin_responses')
    op.drop_index('ix_checkin_resp_user_id', table_name='checkin_responses')
    op.drop_index('ix_checkin_resp_user_date', table_name='checkin_responses')
    op.drop_index('ix_checkin_resp_dimension', table_name='checkin_responses')
    op.drop_index('ix_checkin_resp_date', table_name='checkin_responses')
    op.drop_table('checkin_responses')
    op.drop_index(op.f('ix_bills_id'), table_name='bills')
    op.drop_table('bills')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_daily_index_date', table_name='daily_indexes')
    op.drop_table('daily_indexes')
    op.drop_index('ix_daily_index_segment', table_name='daily_index')
    op.drop_index(op.f('ix_daily_index_id'), table_name='daily_index')
    op.drop_index('ix_daily_index_date', table_name='daily_index')
    op.drop_table('daily_index')
    # ### end Alembic commands ###
